version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: docutils
    versions:
    - "0.17"
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: singledispatch
    versions:
    - 3.6.0
  - dependency-name: watchdog
    versions:
    - 1.0.2
    - 2.0.0
    - 2.0.1
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: packaging
    versions:
    - "20.8"
    - "20.9"
  - dependency-name: pytz
    versions:
    - "2020.5"
    - "2021.1"
  - dependency-name: pyyaml
    versions:
    - 5.4.1
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: chardet
    versions:
    - 4.0.0
