# Set autobuild to false if you do not want to enable compilation when a file changes.
# This will enable http authentication if credentials section is filled.
autobuild: true

# Add files and folders you want autobuild watcher to ignore on changes.
ignore:
  - .git

# Add a username and a password if you want to enable http authentication.
# This will not work if autobuild is enabled.
credentials:
  username: ~
  password: ~
