version: '3'
services:
  graylog-documentation:
    build: .
    image: graylog/documentation
    container_name: graylog-documentation
    init: true
    ports:
      - "8000:8000"
    volumes:
      - .:/web

